//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsFeedApplication.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Category
    {
        public Category()
        {
            this.News = new HashSet<News>();
        }
    
        public int CategoryId { get; set; }

        [Required(ErrorMessage="Category Name is required")]
        [Display(Name = "Category Name")]
        public string CategoryName { get; set; }
    
        public virtual ICollection<News> News { get; set; }
    }
}
